// plugins/tauri/src/SessionCard.svelte
<script lang="ts">
  import type { DisplaySession } from "./lib/types";

  interface Props {
    session: DisplaySession;
    selected: boolean;
  }

  let { session, selected }: Props = $props();

  const sourceBadgeColor = $derived(
    session.sourceLabel === "OC" || session.sourceLabel === "CX" ? "#89b4fa" : "#f9e2af"
  );

  const subagentColor = "#cba6f7";
</script>

<div class="session-card" class:selected aria-selected={selected}>
  <!-- Left accent bar -->
  <div class="accent-bar" style="background: {session.statusColor}"></div>

  <!-- Card body -->
  <div class="card-body">
    <!-- Line 1: name, subagents, source badge, status, time -->
    <div class="card-line card-line-top">
      <span class="project-name">{session.displayName}</span>

      {#if session.subagentCount > 0}
        <span class="subagent-badge" style="color: {subagentColor}">
          [{session.subagentCount}]
        </span>
      {/if}

      <span
        class="source-badge"
        style="color: {sourceBadgeColor}"
      >{session.sourceLabel}</span>

      <span class="status-label" style="color: {session.statusColor}">
        {session.statusLabel}
      </span>

      <span class="spacer"></span>

      <span class="rel-time">{session.relativeTime}</span>
    </div>

    <!-- Line 2: branch / context -->
    <div class="card-line card-line-bottom">
      <span class="branch">{session.branch}</span>

      {#if session.contextLine}
        <span class="sep"> / </span>
        <span class="context-line">{session.contextLine}</span>
      {/if}
    </div>
  </div>
</div>

<style>
  .session-card {
    display: flex;
    align-items: stretch;
    border-bottom: 1px solid rgba(69, 71, 90, 0.25);
    transition: background 80ms ease;
    cursor: default;
  }

  .session-card:last-child {
    border-bottom: none;
  }

  .session-card.selected {
    background: #313244; /* --surface0 */
  }

  .session-card:not(.selected):hover {
    background: rgba(49, 50, 68, 0.5);
  }

  /* ── Accent bar ──────────────────────────────────────────────────────────── */

  .accent-bar {
    width: 4px;
    flex-shrink: 0;
    border-radius: 0;
  }

  /* ── Card body ───────────────────────────────────────────────────────────── */

  .card-body {
    flex: 1;
    min-width: 0;
    padding: 7px 12px 6px 10px;
    display: flex;
    flex-direction: column;
    gap: 3px;
  }

  /* ── Line 1 ──────────────────────────────────────────────────────────────── */

  .card-line {
    display: flex;
    align-items: baseline;
    gap: 5px;
    min-width: 0;
    white-space: nowrap;
    overflow: hidden;
  }

  .project-name {
    font-weight: 700;
    color: #cdd6f4; /* --text */
    overflow: hidden;
    text-overflow: ellipsis;
    flex-shrink: 1;
    min-width: 0;
    max-width: 160px;
  }

  .subagent-badge {
    font-size: 11px;
    font-weight: 600;
    flex-shrink: 0;
  }

  .source-badge {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.04em;
    border: 1px solid currentColor;
    border-radius: 3px;
    padding: 0 3px;
    line-height: 1.4;
    flex-shrink: 0;
    opacity: 0.9;
  }

  .status-label {
    font-size: 11px;
    font-weight: 600;
    flex-shrink: 0;
  }

  .spacer {
    flex: 1;
  }

  .rel-time {
    font-size: 11px;
    color: #7f849c; /* --overlay1 */
    flex-shrink: 0;
    text-align: right;
  }

  /* ── Line 2 ──────────────────────────────────────────────────────────────── */

  .card-line-bottom {
    font-size: 11px;
    color: #a6adc8; /* --subtext */
    overflow: hidden;
  }

  .branch {
    color: #6c7086; /* --gray */
    flex-shrink: 0;
  }

  .sep {
    color: #45475a; /* --surface1 */
    flex-shrink: 0;
  }

  .context-line {
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 1;
    min-width: 0;
  }
</style>

// plugins/ags/widget/SessionCard.tsx
import { Session } from "../lib/types.js";

interface SessionCardProps {
  session: Session;
  selected: boolean;
  onActivate: () => void;
}

/**
 * Renders a single session card with:
 * - Left accent bar colored by status
 * - Name (bold), subagent count (purple), source badge, status label, relative time
 * - Second line: branch / context
 */
export default function SessionCard({ session, selected, onActivate }: SessionCardProps) {
  const s = session;
  const bgCss = selected ? "background-color: #313244;" : "";

  // Source badge color: CC = amber, OC = blue
  const sourceBadgeColor = s.sourceLabel === "OC" ? "#89b4fa" : "#f9e2af";

  // Subagent label (purple) — only shown when > 0
  const agentLabel =
    s.subagentCount > 0
      ? `[${s.subagentCount} agent${s.subagentCount === 1 ? "" : "s"}]`
      : "";

  // Second line: branch / context
  const secondLine =
    s.contextLine ? `${s.branch}  /  ${s.contextLine}` : s.branch;

  return (
    <button
      cssClasses={["session-card", selected ? "selected" : ""]}
      css={bgCss}
      onClicked={onActivate}
    >
      <box orientation={1 /* VERTICAL */} spacing={0}>
        {/* Row 1: accent bar + name + badges + status + time */}
        <box orientation={0 /* HORIZONTAL */} spacing={0} cssClasses={["card-row1"]}>
          {/* Left accent bar */}
          <box
            cssClasses={["accent-bar"]}
            css={`background-color: ${s.statusColor}; min-width: 3px; min-height: 36px;`}
          />
          <box
            orientation={0}
            spacing={6}
            hexpand={true}
            css="padding: 4px 8px 2px 8px;"
          >
            {/* Project name */}
            <label
              label={s.displayName}
              cssClasses={["card-name"]}
              xalign={0}
              css="font-weight: bold;"
            />

            {/* Agent count (purple) */}
            {agentLabel !== "" && (
              <label
                label={agentLabel}
                cssClasses={["card-agents"]}
                css="color: #cba6f7; font-size: 0.85em;"
              />
            )}

            {/* Source badge */}
            <label
              label={s.sourceLabel}
              cssClasses={["card-source"]}
              css={`color: ${sourceBadgeColor}; font-size: 0.8em; font-weight: bold;`}
            />

            {/* Spacer */}
            <box hexpand={true} />

            {/* Status label */}
            <label
              label={s.statusLabel}
              cssClasses={["card-status"]}
              css={`color: ${s.statusColor}; font-size: 0.85em;`}
            />

            {/* Relative time */}
            <label
              label={s.relativeTime}
              cssClasses={["card-time"]}
              css="color: #6c7086; font-size: 0.8em; margin-left: 8px;"
            />
          </box>
        </box>

        {/* Row 2: branch / context */}
        <box orientation={0} css="padding: 0 8px 4px 19px;">
          <label
            label={secondLine}
            cssClasses={["card-context"]}
            css="color: #a6adc8; font-size: 0.82em;"
            xalign={0}
            ellipsize={3 /* END */}
            maxWidthChars={80}
          />
        </box>
      </box>
    </button>
  );
}
